version: '3.3'

volumes:
  postegre_vol:
    external: true

networks:
  postgre_network:
    external:
      name: postgre_network

services:
  postgre:
    image: postgres:${TAG}
    restart: always
    container_name: postgre
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
    volumes:
      - 'postegre_vol:/var/lib/postgresql/data'
    networks:
      - postgre_network


  #adminer:
  #  image: adminer
  #  restart: always
  #  ports:
  #    - 8080:8080