version: '3.3'

volumes:
  postegre_volume:
    external:
      name: postegre_vol

networks:
  review_network:
    external:
      name: review_network

services:
  review:
    image: eliezer123/review:v1
    restart: always
    container_name: review
    ports:
      - '8282:80'
    depends_on:
      - postgres
    networks:
      - review_network
    environment:
      ConnectionStrings__MyConnection: Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};

  postgres:
    image: postgres:${TAG}
    restart: always
    container_name: postgre
    #ports:
    #  - '5432:5432'
    volumes:
      - 'postegre_volume:/var/lib/postgresql/data'
    networks:
      - review_network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

