version: '3.3'

services:
  mongo-express:
    image: mongo-express:0.54
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    networks:
      default:
        aliases:
          - mongodb_network
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: Demo123@
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      



