version: '3.3'

volumes:
  mongo_volume:
    external:
      name: mongo_vol

networks:
  application_network:
    external:
      name: application_network

services:
  web:
    image: 'eliezer123/rotten-potatoes:latest'
    restart: always
    ports:
      - '80:5000'
    networks:
      - application_network
    depends_on:
      - mongodb
    environment:
      MONGODB_DB: "admin"
      MONGODB_HOST: "mongodb"
      MONGODB_PORT: "27017"
      MONGODB_USERNAME: mongodbuser
      MONGODB_PASSWORD: mongodbpwd

  mongodb:
    image: mongo:4.4.3
    restart: always
    networks:
      - application_network
    volumes:
      - mongo_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: mongodbpwd
