version: '3.3'

networks:
  postgre_network:
    external:
      name: postgre_network

services:
  mongo-express:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    ports:
      - 80:80
    networks:
      - postgre_network
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
