version: '3.3'

networks:
  mariadb_network:
    external:
      name: mariadb_network

services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin
    ports:
      - '8080:80'
    networks:
      - mariadb_network
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb