version: '3.3'

volumes:
  mongodb_vol:
    external: true

networks:
  mongodb_network:
    external:
      name: mongodb_network

services:
  mongodb:
    image: mongo:${TAG}
    restart: always
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_vol:/data/db'
    networks:
      - mongodb_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD}
