version: '3.3'

#Volume a ser utilizado no redis
volumes:
  redis_vol:
    external: true

services:
  redis:
    image: redis:${TAG}
    restart: always
    container_name: redis
    #Necessário fazer port-bind se voce irá acessar de forra do container, 
    # neste caso na Questao02 tem a interface do redis para acessar
    #ports:
    #  - '6380:6379'
    #Definindo a qual network ficará atrelado
    networks:
      - redis_network
    volumes:
      - 'redis_vol:/data'
    command: redis-server --save 60 1

#Defininição das networks a serem usadas
networks:
  #Network do redis
  redis_network:
    external:
      name: redis_nwk