version: '3.3'

volumes:
  mariadb_vol:
    external: true
    
services:
  mariadb:
    image: 'mariadb:${TAG}'
    restart: always
    container_name: mariadb
    networks:
      default:
        aliases:
          - mariadb_network
    environment:
      MARIADB_ROOT_PASSWORD: ${PASSWORD}
    volumes:
      - mariadb_vol:/var/lib/mysql
    ports:
      - '3306:3306'


